### ISSUE TITLE
请问如何把参考文献改为IEEE格式？

### ISSUE THREAD

**Issue by sjtuminhang** [sjtug/SJTUThesis#359]
**问题描述**:
请问如何把参考文献改为IEEE格式？

**系统信息**:

- OS版本(带版本号): macOS/Windows/Linux
- TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX

**日志信息**:

**Comment by hushidong** [comment]
把参考文献样式从gb7714-2015换成ieee即可。 hzzmail 邮箱：hzzmail@sjtu.org 签名由 网易邮箱大师 定制 在2018年08月15日 17:42，sjtuminhang 写道： 问题描述: 请问如何把参考文献改为IEEE格式？ 系统信息: OS版本(带版本号): macOS/Windows/Linux TeX 发行版(带版本号): TeX Live/MiKTeX/MacTeX 日志信息: — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sjtuminhang** [comment]
谢谢，参考文献的题目如何由英文"Bibliography"变成中文的"参考文献"呢？

**Comment by AlexaraWu** [comment]
设置 `\printbibliography` 的选项即可:
```latex
\printbibliography[heading=bibintoc,title={参考文献}]
```

**Comment by sjtuminhang** [comment]
非常感谢！
